"""add artifacts table

Revision ID: 5f96f6375baf
Revises: 06c076b5aec7
Create Date: 2026-06-15 20:49:40.850245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f96f6375baf'
down_revision: Union[str, Sequence[str], None] = '06c076b5aec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('artifact_type', sa.Enum('STORED_PROCEDURE', 'VIEW', 'FUNCTION', 'TABLE', 'DDL', 'SQL_FILE', name='artifacttype'), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PARSING', 'PARSED', 'GENERATING', 'GENERATED', 'FAILED', name='artifactstatus'), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_index(op.f('ix_artifacts_artifact_id'), 'artifacts', ['artifact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_artifact_id'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
