"""add generated artifacts table

Revision ID: 65932b60d32b
Revises: fe56be9eb158
Create Date: 2026-06-17 00:11:15.876825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65932b60d32b'
down_revision: Union[str, Sequence[str], None] = 'fe56be9eb158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_artifacts',
    sa.Column('generated_artifact_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.artifact_id'], ),
    sa.PrimaryKeyConstraint('generated_artifact_id')
    )
    op.create_index(op.f('ix_generated_artifacts_generated_artifact_id'), 'generated_artifacts', ['generated_artifact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_artifacts_generated_artifact_id'), table_name='generated_artifacts')
    op.drop_table('generated_artifacts')
    # ### end Alembic commands ###
