"""add analysis runs table

Revision ID: 9133f1a74d09
Revises: 5f96f6375baf
Create Date: 2026-06-16 00:16:48.999725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9133f1a74d09'
down_revision: Union[str, Sequence[str], None] = '5f96f6375baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.Enum('PARSER', 'DEPENDENCY', 'DBT_GENERATION', 'VALIDATION', name='analysistype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.artifact_id'], ),
    sa.PrimaryKeyConstraint('analysis_run_id')
    )
    op.create_index(op.f('ix_analysis_runs_analysis_run_id'), 'analysis_runs', ['analysis_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_runs_analysis_run_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
